/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Module2;

/**
 *
 * @author Admin
 */
public class Bai1_4 extends javax.swing.JFrame implements Bai1_4_Interface{
    
    /**
     * Creates new form Bai4
     */
    public Bai1_4() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSoThuNhat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSoThuHai = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTong = new javax.swing.JTextField();
        jbTong = new javax.swing.JButton();
        jbTru = new javax.swing.JButton();
        jbChia = new javax.swing.JButton();
        jbNhan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Số thứ nhất");

        jLabel2.setText("Số thứ hai");

        jLabel3.setText("Kết quả");

        jbTong.setText("Tổng");
        jbTong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTongActionPerformed(evt);
            }
        });

        jbTru.setText("Trừ");
        jbTru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTruActionPerformed(evt);
            }
        });

        jbChia.setText("Chia");
        jbChia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbChiaActionPerformed(evt);
            }
        });

        jbNhan.setText("Nhân");
        jbNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(txtTong, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(txtSoThuHai, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(txtSoThuNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(366, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbNhan)
                        .addGap(37, 37, 37)
                        .addComponent(jbChia))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbTong)
                        .addGap(37, 37, 37)
                        .addComponent(jbTru)))
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSoThuNhat, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbTong)
                    .addComponent(jbTru))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSoThuHai, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbChia)
                    .addComponent(jbNhan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTong, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(187, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbTongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTongActionPerformed
        // TODO add your handling code here:
        int soThuNhat = Integer.parseInt(txtSoThuNhat.getText());
        int soThuHai = Integer.parseInt(txtSoThuHai.getText());
        Bai1_4_Interface op = (Integer o1, Integer o2) -> o1 + o2;
        int tong = op.operator(soThuNhat, soThuHai);
        txtTong.setText(String.valueOf(tong));
        jLabel3.setText("Tổng");
    }//GEN-LAST:event_jbTongActionPerformed

    private void jbTruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTruActionPerformed
        // TODO add your handling code here:
        int soThuNhat = Integer.parseInt(txtSoThuNhat.getText());
        int soThuHai = Integer.parseInt(txtSoThuHai.getText());
        Bai1_4_Interface op = (Integer o1, Integer o2) -> o1 - o2;
        int tru = op.operator(soThuNhat, soThuHai);
        txtTong.setText(String.valueOf(tru));
        jLabel3.setText("Trừ");
    }//GEN-LAST:event_jbTruActionPerformed

    private void jbChiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbChiaActionPerformed
        // TODO add your handling code here:
        int soThuNhat = Integer.parseInt(txtSoThuNhat.getText());
        int soThuHai = Integer.parseInt(txtSoThuHai.getText());
        Bai1_4_Interface op = (Integer o1, Integer o2) -> o1 / o2;
        int chia = op.operator(soThuNhat, soThuHai);
        txtTong.setText(String.valueOf(chia));
        jLabel3.setText("Chia");
    }//GEN-LAST:event_jbChiaActionPerformed

    private void jbNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNhanActionPerformed
        // TODO add your handling code here:
        int soThuNhat = Integer.parseInt(txtSoThuNhat.getText());
        int soThuHai = Integer.parseInt(txtSoThuHai.getText());
        Bai1_4_Interface op = (Integer o1, Integer o2) -> o1 * o2;
        int nhan = op.operator(soThuNhat, soThuHai);
        txtTong.setText(String.valueOf(nhan));
        jLabel3.setText("Nhân");
    }//GEN-LAST:event_jbNhanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai1_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai1_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai1_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai1_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai1_4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbChia;
    private javax.swing.JButton jbNhan;
    private javax.swing.JButton jbTong;
    private javax.swing.JButton jbTru;
    private javax.swing.JTextField txtSoThuHai;
    private javax.swing.JTextField txtSoThuNhat;
    private javax.swing.JTextField txtTong;
    // End of variables declaration//GEN-END:variables

    @Override
    public Integer operator(Integer o1, Integer o2) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
